export default {
  homePage: "/",
  singleBook: "/singleBook/:id",
  singleNews: "/singleNews/:id",
  news: "/news",
  books: "/books",
  directories: "/directories",
  writingChallenge: "/writingChallenge",
  addNews: "/addNews",
  addBooks: "/addBooks",
  addDirectories: "/addDirectories",
  addWritingChallenge: "/addWritingChallenge",
  writingChallengeQuestions: "/writingChallengeQuestions",
  adminPannel: "/adminPannel",
  AboutUs: "/AboutUs",
  termsAndConditions: "/termsAndConditions",
  aboutUs: "/aboutUs",
  privacyPolicy: "/privacyPolicy",
  contactUs: "/contactUs",
  levels: "/levels",
  quizes: "/quizes",
  quizCategories: "/quizCategories",
  addQuiz: "/addQuiz",
};
